import { BarChart3, Bot, MapPin, Megaphone, MonitorSmartphone, Search } from "lucide-react";

export const services = [
  { slug: "google-maps-optimization", icon: MapPin, title: "Google Maps Optimization", navDescription: "Show up when the local customers you want are ready to call", eyebrow: "Targeted local visibility", headline: "Get found by the local customers and jobs you want most.", body: "Google Maps optimization built to put your business in front of qualified searchers in the service areas you choose—so the right nearby customers call you before a competitor.", points: ["Targeted service-area visibility", "Google Business Profile optimization", "Review and photo strategy"], outcomes: ["Visibility for your highest-value services", "Reach across the locations you want to serve", "More qualified calls from local search"] , process: ["Define your ideal jobs, customers, and service areas", "Optimize categories, services, content, photos, and trust signals", "Monitor which searches produce qualified calls and keep improving"] },
  { slug: "ai-seo-google-seo", icon: Search, title: "AI SEO & Google SEO", navDescription: "Get recommended to the right customers in Google and AI search", eyebrow: "Qualified search visibility", headline: "Become the answer your ideal customers find—and call.", body: "AI SEO plus traditional Google SEO focused on the exact services, locations, and high-intent searches that match the business you want more of.", points: ["Targeted service and city pages", "AI answer-engine visibility", "High-intent keyword targeting"], outcomes: ["Organic traffic that matches your ideal customer", "Recommendations in Google and AI answers", "Search pages that turn qualified visits into calls"], process: ["Research the customers, jobs, and markets you want", "Build pages around their highest-intent searches", "Measure qualified calls and strengthen what produces them"] },
  { slug: "google-meta-ads", icon: Megaphone, title: "Targeted Meta & Google Ads", navDescription: "Paid campaigns that make the people you want call", eyebrow: "Precision paid acquisition", headline: "Make the customers you want see you, trust you, and call.", body: "Google and Meta campaigns targeted around your ideal customer, profitable job types, and chosen service areas—not broad traffic or empty clicks.", points: ["Ideal-customer and service-area targeting", "Call-focused Google and Meta campaigns", "Creative built to pre-qualify callers"], outcomes: ["Qualified calls from the customers you want", "Fewer irrelevant inquiries and wasted clicks", "Budget concentrated on profitable services and locations"], process: ["Define your ideal caller and most valuable jobs", "Launch targeted campaigns and qualification-focused pages", "Track call quality and move budget toward the best opportunities"] },
  { slug: "web-landing-pages", icon: MonitorSmartphone, title: "Web & Landing Page Development", navDescription: "Pages that speak directly to your ideal customer and prompt a call", eyebrow: "Qualified conversion design", headline: "Turn the right visitors into qualified callers.", body: "Fast, mobile-first pages with messaging that speaks to the customers and jobs you want, filters out poor-fit inquiries, and makes calling the natural next step.", points: ["Ideal-customer messaging", "Tap-to-call mobile layouts", "Conversion-first copy and hosting"], outcomes: ["A journey designed for your ideal customer", "More qualified calls from your existing traffic", "Clear expectations that reduce poor-fit inquiries"], process: ["Clarify who you want calling and what they need", "Design a focused experience that builds trust and fit", "Track qualified calls and improve conversion points"] },
  { slug: "ai-automation", icon: Bot, title: "AI Automation Suite", navDescription: "Answer, qualify, follow up, and book the right leads around the clock", eyebrow: "24/7 qualification", headline: "Know who is calling—and which opportunities deserve attention.", body: "A 24/7 AI Phone Receptionist that answers every call, qualifies the customer, job, and location against your criteria, then books the opportunities you want.", points: ["24/7 AI Phone Receptionist", "Custom caller qualification", "AI chat, text, email, and CRM nurturing"], outcomes: ["Every caller answered and qualified", "More appointments with the right prospects", "Less time spent on poor-fit inquiries"], process: ["Define your qualification rules, service areas, and calendar", "Configure AI conversations and follow-up sequences", "Review call quality and improve booking performance"] },
  { slug: "call-tracking-analytics", icon: BarChart3, title: "Call Tracking & Analytics", navDescription: "Know which campaigns produce the qualified callers you want", eyebrow: "Call quality clarity", headline: "See what attracts your best callers—and scale it with confidence.", body: "Reporting that connects every call to its ad, keyword, page, service, and location, then helps you distinguish qualified opportunities from irrelevant volume.", points: ["Source tracking by campaign", "Call recordings and qualification outcomes", "Qualified cost-per-call reporting"], outcomes: ["A clear view of call volume and quality", "Proof of which channels attract ideal customers", "Smarter investment in the services and markets that fit"], process: ["Connect tracking to every campaign and conversion page", "Attribute and qualify calls by source, service, and location", "Scale the sources producing your best-fit opportunities"] },
] as const;

export function getService(slug: string) { return services.find((service) => service.slug === slug); }
